spring:
  application:
    name: client


server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/,http://peer3:8083/eureka/

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://peer1/eureka/,http://peer2/eureka/,http://peer3/eureka/

logging:
  level:
    root: debug
