spring:
  application:
    name: client
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8070
management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS


server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/,http://peer3:8083/eureka/

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://peer1/eureka/,http://peer2/eureka/,http://peer3/eureka/

logging:
  level:
    root: info

