spring:
  application:
    name: eureka-client
  profiles: eureka-client-profile
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jmx:
    enabled: false
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

